### ISSUE TITLE
building error 

### ISSUE THREAD

**Issue by gotjawal** [brummer10/bluesbreaker.lv2#1]
g++ -fPIC -DPIC -O2 -Wall -funroll-loops -fomit-frame-pointer -fstrength-reduce -fstack-protector -fvisibility=hidden -fdata-sections -Wl,--gc-sections -Wl,--exclude-libs,ALL bluesbreaker.cpp -fvisibility=hidden -shared -lm -fPIC -Wl,-z,noexecstack -Wl,--no-undefined -Wl,--gc-sections -o bluesbreaker.so
bluesbreaker.cpp:8:10: fatal error: lv2.h: No such file or directory
    8 | #include <lv2.h>
      |          ^~~~~~~
compilation terminated.
make[1]: *** [makefile:104: bluesbreaker] Error 1
make[1]: Leaving directory '/home/ray/src/bluesbreaker.lv2/bluesbreaker'
make: *** [makefile:34: bluesbreaker] Error 2

**Comment by brummer10** [comment]
You need to install lv2-dev

**Comment by gotjawal** [comment]
Thanks for reply,

My distro is archlinux and installed packages are  lv2, lv2file, lv2lint, lvtk, lilv.
are any other packages needed?

**Comment by gotjawal** [comment]
modified header like below...it works 
bluesbreaker.cpp line 8

#include <lv2/core/lv2.h>

**Comment by brummer10** [comment]
The issue is that LV2 0.18.6 no longer provides a top-level lv2.h
That is a real deal breaker. I guess we will see a lot of bug reports for that in the next time. 
Even with your fix above, noon knows how long that works. Even when switch back to the old style like

#include <lv2/lv2plug.in/ns/lv2core/lv2.h>

we don't know if that will change any time sooner or later. A real deal breaker.
